apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-pro-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-pro
  template:
    metadata:
      labels:
        app: react-pro
    spec:
      containers:
        - name: react-pro
          image: 127.0.1.1:8081/repository/ReactDockerHost/
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: NEXUS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: react-app-secret
                  key: username
            - name: NEXUS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: react-app-secret
                  key: password
      imagePullSecrets:
        - name: react-app-secret

