apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-pro
  labels:
    app: react-pro-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-pro-app
  template:
    metadata:
      labels:
        app: react-pro-app
    spec:
      containers:
      - name: react-pro
        image: 127.0.1.1:8082/react-pro:latest
        ports:
        - containerPort: 80
